### ISSUE TITLE
Unsuccessful HTTP response

### ISSUE THREAD

**Issue by kevingilbert100** [amaurymartiny/react-redux-auth0-kit#16]
Any idea whats going on here?

<img width="1197" alt="screen shot 2018-01-30 at 1 14 50 am" src="https://user-images.githubusercontent.com/22782371/35552802-111582da-055b-11e8-8d7b-b5ae397bd925.png">

**Comment by kevingilbert100** [comment]
Hmm - So I was able to get this working perfectly by updating the lock to the latest version and changing ```idToken``` to ```accessToken``` in the AppView.js file.

**Comment by Nuruddinjr** [comment]
Hey, how to fix No access control allow origin error
