### ISSUE TITLE
"404" flashes for a second

### ISSUE THREAD

**Issue by HoraceShmorace** [amaurymartiny/react-redux-auth0-kit#19]
After a few days of casual research, I've settle on this as the best boilerplate out there for Auth0 Embedded Login in a React/Redux app. Thank you.

One small issue: right after logging in, the page title flashes "404" just for maybe a second. Just FYI.

**Comment by amaury1093** [comment]
Thanks!

Yes, I am aware of this issue. It should be fairly easy to show a loading page during this phase. For minimalism's sake I prefer not to implement it in this repo.
