### ISSUE TITLE
About won't render

### ISSUE THREAD

**Issue by rogueturnip** [amaurymartiny/react-redux-auth0-kit#4]
I was able to get everything set up and working but the about link isn't re-rendering, even on a reload.  In the Route line I added an "exact" for the '/' path and that now makes it render when reloaded but the links don't cause the page to reload.

Any suggestions?

**Comment by rogueturnip** [comment]
I see you committed some changes to AppView.js and other files to address the router issues but for some reason when I do a git clone I'm not getting these changes.

**Comment by amaury1093** [comment]
Good catch. The `withRouter` HOC should wrap outside of `connect`, as per the `react-router-dom` documentation.

See ff02e7f for diff.

Tell me if this is fixed or not.

**Comment by rogueturnip** [comment]
That did the trick.  I figured it was the shouldcomponentupdate setting but didn't see the wrapping bit inside the documentation.. Thanks!
