### ISSUE TITLE
Token parameter needed?

### ISSUE THREAD

**Issue by benschaaf** [amaurymartiny/react-redux-auth0-kit#8]
On https://github.com/amaurymartiny/react-redux-auth0-kit/blob/master/src/utils/AuthService.js#L88, a call to _getTokenExpirationDate_ passes  _token_, as seen below:
`const date = AuthService.getTokenExpirationDate(token)`
However, getTokenExpirationDate does not appear to do anything with the token.
` static getTokenExpirationDate() { ... }`

But, I could be missing something. I can very quickly throw together a PR, if this is confirmed as a issue.

**Comment by amaury1093** [comment]
Good catch. Yes, PR much appreciated :)

**Comment by benschaaf** [comment]
Merged and closing.
